# Secret para PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: postgres
type: Opaque
data:
  # echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=